# Generated by Django 3.1.7 on 2021-04-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='username',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
