# Generated by Django 3.1.7 on 2021-04-07 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Languagetolearn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_slot', models.DateTimeField()),
                ('start_time_slot', models.DateTimeField()),
                ('end_time_slot', models.DateTimeField()),
                ('id_child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.child')),
                ('id_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.language')),
            ],
        ),
        migrations.DeleteModel(
            name='Languagelearn',
        ),
    ]
