# Generated by Django 3.1.7 on 2021-04-14 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='languagetolearn',
            old_name='last_name',
            new_name='child',
        ),
    ]
