# Generated by Django 3.1.7 on 2021-04-14 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.language'),
        ),
        migrations.AlterField(
            model_name='languagetolearn',
            name='correspondent_language',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='correspondent_language', to='main.language'),
        ),
        migrations.AlterField(
            model_name='languagetolearn',
            name='link_video',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
