# Generated by Django 3.1.7 on 2021-04-15 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_slot',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='end_time_slot',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='language',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='main.language'),
        ),
        migrations.AlterField(
            model_name='message',
            name='start_time_slot',
            field=models.TimeField(blank=True),
        ),
    ]
