# Generated by Django 3.1.7 on 2021-04-09 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_parent_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='username',
        ),
    ]
