# Generated by Django 3.1.7 on 2021-04-13 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_languagetolearn_child'),
    ]

    operations = [
        migrations.AddField(
            model_name='languagetolearn',
            name='child',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.child'),
        ),
    ]
