# Generated by Django 3.1.7 on 2021-04-15 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210415_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='message',
            name='date_slot',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='end_time_slot',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='start_time_slot',
            field=models.TimeField(null=True),
        ),
    ]
