# Generated by Django 3.1.7 on 2021-04-09 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_parent_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='emailEERR',
        ),
        migrations.AddField(
            model_name='child',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
