# Generated by Django 3.1.7 on 2021-04-05 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210404_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='child',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.parent'),
        ),
        migrations.AddField(
            model_name='parent',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='languagetolearn',
            field=models.ManyToManyField(default='English', to='main.Language'),
        ),
        migrations.AlterField(
            model_name='child',
            name='native_language',
            field=models.CharField(default='English', max_length=100),
        ),
        migrations.AlterField(
            model_name='child',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='child',
            name='pseudo',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date sent'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='visio',
            name='visio_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
