# Generated by Django 3.1.7 on 2021-04-05 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210405_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='country',
            field=models.CharField(default='USA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='street',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='zipcode',
            field=models.IntegerField(null=True),
        ),
    ]
