# Generated by Django 3.1.7 on 2021-04-09 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_parent_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='age',
        ),
        migrations.AddField(
            model_name='child',
            name='birthdate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='hobbies',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='language_to_learn',
            field=models.CharField(choices=[('English', 'English'), ('Mandarin', 'Mandarin'), ('Spanish', 'Spanish')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='child',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.parent'),
        ),
    ]
