# Generated by Django 3.1.7 on 2021-04-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210405_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='birthdate',
            field=models.DateTimeField(null=True),
        ),
    ]
