# Generated by Django 3.1.7 on 2021-04-10 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210409_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='date_joined',
        ),
        migrations.AlterField(
            model_name='child',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='child',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='child',
            name='native_language',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='child',
            name='parent',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='main.parent'),
        ),
    ]
