# Generated by Django 3.1.7 on 2021-04-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_merge_20210405_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='languagetolearn',
            field=models.ManyToManyField(default='English', to='main.Language'),
        ),
    ]
